name: GitHub GitLab Mirror

on:
  push:
    branches: [ master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub GitLab Mirror
      uses: neture/GitHub-GitLab-Mirror@master
      with:
        args: "https://git.neture.ch/vaorra/ragemp-server"
      env:
        GITLAB_HOSTNAME: "git.neture.ch"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "18"
